config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index', :locale => /es|en/, as: :redirected_root, via: [:get]
  match '/home', to: 'home#index', :locale => /es|en/, via: [:get]
  match ':locale/home', to: 'home#index', :locale => /es|en/, via: [:get]

  match '/alr_admin', to: 'alr_admin/alr_admin#index', :locale => /es|en/, via: [:get]
  match '/(:locale)/alr_admin', to: 'alr_admin/alr_admin#index', :locale => /es|en/, via: [:get]

  match '/blog', to: 'blog/blog#index', :locale => /es|en/, via: [:get]
  match '/(:locale)/blog', to: 'blog/blog#index', :locale => /es|en/, via: [:get]

  match '/admin', to: 'alr_admin/home#index', :locale => /es|en/, via: [:get]
  match '/(:locale)/admin', to: 'alr_admin/home#index', :locale => /es|en/, via: [:get]
  
  scope "(:locale)", :locale => /es|en/ do
    #namspace for staff-admins.
    namespace :alr_admin do
        get 'admin', to: 'alr_admin/home#index'
    end

    #namespace for blog
    namespace :blog do
    end

    #namespace for demo admin and sandbox;
    namespace :admin do
    end

    #routes for the demos

    get '/about', to: 'home#about'

    get '/widgets', to: 'home#widgets'
    #Base CSS
    get '/grid_system', to: 'home#grids'
    get '/typography', to: 'home#typography'
    get '/icons', to: 'home#icons'
    get '/colors', to: 'home#colors'
    get '/helpers', to: 'home#helpers'
    get '/rtl', to: 'home#rtl'
    #Data operative
    get '/tables', to: 'home#tables'
    get '/forms', to: 'home#forms'
    get '/buttons', to: 'home#buttons'
    get '/donut_chart', to: 'home#donut_chart'
    get '/progressbar', to: 'home#progressbar'
    get '/button_groups', to: 'home#button_groups'
    get '/keypad', to: 'home#keypad'
    #---------------------------------------------
    get '/form_validation', to: 'home#form_validation'
    get '/draggable', to: 'home#draggable'
    get '/events', to: 'home#events'
    get '/hotkeys', to: 'home#hotkeys'
    #Visuals
    get '/charms', to: 'home#charms'
    get '/tiles', to: 'home#tiles'
    get '/carousel', to: 'home#carousel'
    get '/panels', to: 'home#panels'
    get '/rating', to: 'home#rating'
    get '/preloaders', to: 'home#preloaders'
    get '/images', to: 'home#images'
    get '/streamer', to: 'home#streamer'
    get '/presenter', to: 'home#presenter'
    #Menus
    get '/appbar', to: 'home#appbar'
    get '/regmenus', to: 'home#regmenus'
    get '/fluentmenus', to: 'home#fluentmenus'
    get '/sidebar', to: 'home#sidebar'
    #Information
    get '/notify', to: 'home#notify'
    get '/dialogs', to: 'home#dialogs'
    get '/windows', to: 'home#windows'
    get '/pops', to: 'home#pops'
    get '/hints', to: 'home#hints'
    #Controls
    get '/accordion', to: 'home#accordion'
    get '/tabs', to: 'home#tabs'
    get '/treeview', to: 'home#treeview'
    get '/listview', to: 'home#listview'
    get '/slider', to: 'home#slider'
    get '/wizards', to: 'home#wizards'
    #Date & time
    get '/calendar', to: 'home#calendar'
    get '/datepicker', to: 'home#datepicker'
    get '/countdown', to: 'home#countdown'
    #Media
    get '/audio_player', to: 'home#audio_player'
    get '/video_player', to: 'home#video_player'
    #Third party
    get '/select2', to: 'home#select2'
    get '/data_tables', to: 'home#data_tables'
    get '/animate', to: 'home#animate'
    #Utils
    get '/dark_mode', to: 'home#dark_mode'
    get '/easing', to: 'home#easing'
    get '/reqjs', to: 'home#reqjs'

    #Templates
    #Admin example see line 13
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/alr_admin/home_controller.rb
class AlrAdmin::HomeController < ApplicationController
	def index
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale
 
  private

  def set_locale
    I18n.locale = params[:locale] || session[:locale] || I18n.default_locale || session[:locale] = I18.locale
    #Rails.application.routes.default_url_options[:locale]= I18n.locale

    if language_change_necessary?
        I18n.locale = the_new_locale
        set_locale_cookie(I18n.locale)
    else
        use_locale_from_cookie
  	end
  end

  def default_url_options(options={})
  	{:locale => I18n.locale}
  end

  # A locale change is necessary if no locale cookie is found, or if the locale param has been specified
  def language_change_necessary?
    return cookies[:locale].nil? || params[:locale]
  end
 # The new locale is taken from the current_user language setting, it logged_in, or from the http accept language header if not
  # In both cases, if a locale param has been passed, it takes precedence. Only available locales are accepted
  def the_new_locale
    new_locale = (params[:locale] || extract_locale_from_accept_language_header)
    ['en', 'es'].include?(new_locale) ? new_locale : I18n.default_locale.to_s
  end

  # Sets the locale cookie
  def set_locale_cookie(locale)
    cookies[:locale] = locale.to_s
  end

  # Reads the locale cookie and sets the locale from it
  def use_locale_from_cookie
    I18n.locale = cookies[:locale]
  end

  # Extracts the locale from the accept language header, if found
  def extract_locale_from_accept_language_header
    locale = request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first rescue I18n.default_locale
  end

  #sourrce https://gist.github.com/jaimeiniesta/194956
  #https://stackoverflow.com/questions/1253468/best-approach-for-localize-images
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end

	def about
	end

	def widgets
	end

	#Base CSS methods
	def grid_system
		
	end

	def typography
		
	end

	def icons
		
	end

	def colors
		
	end

	def helpers
		
	end

	def rtl
		
	end

	#Data operative
	def tables
		
	end

	def forms
		
	end

	def buttons
		
	end

	def donut_chart
		
	end

	def progressbar
		
	end

	def button_groups
		
	end

	def keypad
		
	end

	def form_validation
		
	end

	def draggable
		
	end

	def events
		
	end

	def hotkeys
		
	end

	#Visuals

	def charms
		
	end

	def tiles
		
	end

	def carousel
		
	end

	def panels
		
	end

	def rating
		
	end

	def preloaders
		
	end

	def images
		
	end

	def streamer
		
	end

	def presenter
		
	end

	#Menus
	def appbar
		
	end

	def regmenus
		
	end

	def fluentmenus
		
	end

	def sidebar
		
	end

	#information

	def notify
		
	end

	def dialogs
		
	end

	def windows
		
	end

	def pops
		
	end

	def hints
		
	end
	#Controls

	def accordion
		
	end

	def tabs
		
	end

	def treeview
		
	end

	def listview
		
	end

	def slider
		
	end

	def wizards
		
	end

	#Date & time

	def calendar
		
	end

	def datepicker
		
	end

	def countdown
		
	end

	#Media
	def audio_player
		
	end

	def video_player
		
	end

	#Third party
	def select2
		
	end

	def data_tables
		
	end

	def animate
		
	end

	#utils

	def dark_mode
		
	end

	def easing
		
	end

	def reqjs
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(page_title)
  		content_for :title, page_title.to_s
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/alr_admin/_bar.html.erb
<div class="app-bar fixed-top alacran" data-role="appbar">
        <a href="/" class="app-bar-element branding"><span class="icn-alacran icn-2x"></span></a>

        <ul class="app-bar-menu">
            <li>
                <a href="#">Build 9052020</a>
            </li>
        </ul>
        <ul class="app-bar-menu place-right" style="margin-right: 10px;">
            <div class="input-control text" style="float: left;">
                <span class="icn-search prepend-icon"></span>
                <input type="text">
            </div>
            <li>
                <a onclick="toggleMetroCharm('#docs-charm')"><span class="icn-menu icn-2x"></span></a>
            </li>
        </ul>

        <span class="app-bar-pull"></span>

</div>

app/views/alr_admin/home/index.html.erb
<%= render 'alr_admin/bar' %>
<%= title t(:admin_home) %>
<h1>ALR Admin</h1>

app/views/home/_bar.html.erb
<div class="app-bar fixed-top alacran" data-role="appbar">
        <a href="/" class="app-bar-element branding"><span class="icn-alacran icn-2x"></span></a>

        <ul class="app-bar-menu">
            <li>
                <a href="#">Build 9052020</a>
            </li>
        </ul>
        <ul class="app-bar-menu place-right" style="margin-right: 10px;">
            <div class="input-control text" style="float: left;">
                <span class="icn-search prepend-icon"></span>
                <input type="text">
            </div>
            <li>
                <a onclick="toggleMetroCharm('#docs-charm')"><span class="icn-menu icn-2x"></span></a>
            </li>
        </ul>

        <span class="app-bar-pull"></span>

</div>
<div data-role="charm" data-position="right" id="docs-charm" class="charm right-side" style="opacity: 1; display: block; right: 0px; left: auto; top: 0px; bottom: 0px; overflow-y: scroll;">
    <ul class="sidebar2">
        <li class="title"><%= t(:docs) %></li>
        <li class="">
            <a class="dropdown-toggle" href="#"><span class="icn-multitrack-audio icon"></span><%= t(:quick_settings) %></a>
                <ul class="d-menu" data-role="dropdown" style="display: none;">
                    <li><a id="homeDarkMode"><span id="homeDarkMode-icn" class="icn-eye_blind"></span> <%= t(:dark_mode_en) %></a></li>
                    <% if I18n.locale == I18n.default_locale %>
                        <li><%= link_to  :locale =>'es'  do %><span class="icn-chevron-right"></span> Español<% end %></li>
                        
                    <% else %>
                        <li><%= link_to  :locale =>'en'  do %><span class="icn-chevron-right"></span> English<% end %></li>
                    <% end %>
                </ul>
        </li>
        <li class="">
            <a class="dropdown-toggle" href="#"><span class="icn-earth_2 icon"></span><%= t(:base_css) %></a>
                <ul class="d-menu" data-role="dropdown" style="display: none;">
                    <li><a href="<%= grid_system_path %>"><%= t(:grid_system) %></a></li>
                    <li><a href="<%= typography_path %>"><%= t(:typography) %></a></li>
                    <li><a href="<%= icons_path %>"><%= t(:icons) %></a></li>
                    <li><a href="<%= colors_path %>"><%= t(:colors) %></a></li>
                    <li><a href="<%= helpers_path %>"><%= t(:helpers) %></a></li>
                    <li><a href="<%= rtl_path %>"><%= t(:rtl) %></a></li>
                </ul>
        </li>
        <li class="">
            <a class="dropdown-toggle" href="#"><span class="icn-widgets icon"></span><%= t(:data) %></a>
            <ul class="d-menu" data-role="dropdown" style="display: none;">
                <li><a href="<%= tables_path %>"><%= t(:tables) %></a></li>
                    <li><a href="<%= forms_path %>"><%= t(:forms) %></a></li>
                    <li><a href="<%= buttons_path %>"><%= t(:buttons) %></a></li>
                    <li><a href="<%= donut_chart_path %>"><%= t(:donut_chart) %></a></li>
                    <li><a href="<%= progressbar_path %>"><%= t(:progressbar) %></a></li>
                    <li><a href="<%= button_groups_path %>"><%= t(:button_groups) %></a></li>
                    <li><a href="<%= keypad_path %>"><%= t(:keypad) %></a></li>
                    <li class="divider"></li>
                     <li><a href="<%= form_validation_path %>"><%= t(:form_validation) %></a></li>
                    <li><a href="<%= draggable_path %>"><%= t(:draggable) %></a></li>
                    <li><a href="<%= events_path %>"><%= t(:events) %></a></li>
                    <li><a href="<%= hotkeys_path %>"><%= t(:hotkeys) %></a></li>
            </ul>
        </li>
        <li class="">
            <a class="dropdown-toggle" href="#"><span class="icn-palette icon"></span><%= t(:visuals) %></a>
            <ul class="d-menu" data-role="dropdown" style="display: none;">
                <li><a href="<%= charms_path %>"><%= t(:charms) %></a></li>
                <li><a href="<%= tiles_path %>"><%= t(:tiles) %></a></li>
                <li><a href="<%= carousel_path %>"><%= t(:carousel) %></a></li>
                <li><a href="<%= panels_path %>"><%= t(:panels) %></a></li>
                <li><a href="<%= rating_path %>"><%= t(:rating) %></a></li>
                <li><a href="<%= preloaders_path %>"><%= t(:preloaders) %></a></li>
                <li><a href="<%= images_path %>"><%= t(:images) %></a></li>
                <li><a href="<%= streamer_path %>"><%= t(:streamer) %></a></li>
                <li><a href="<%= presenter_path %>"><%= t(:presenter) %></a></li>
            </ul>
        </li>
        <li class="">
            <a class="dropdown-toggle" href="#"><span class="icn-list_2 icon"></span><%= t(:menus) %></a>
            <ul class="d-menu" data-role="dropdown" style="display: none;">
                <li><a href="<%= appbar_path %>"><%= t(:appbar) %></a></li>
                <li><a href="<%= regmenus_path %>"><%= t(:regmenus) %></a></li>
                <li><a href="<%= fluentmenus_path %>"><%= t(:fluentmenus) %></a></li>
                <li><a href="<%= sidebar_path %>"><%= t(:sidebar) %></a></li>
            </ul>
        </li>
        <li class="">
            <a class="dropdown-toggle" href="#"><span class="icn-notification icon"></span><%= t(:information) %></a>
            <ul class="d-menu" data-role="dropdown" style="display: none;">
                <li><a href="<%= notify_path %>"><%= t(:notify) %></a></li>
                <li><a href="<%= dialogs_path %>"><%= t(:dialogs) %></a></li>
                <li><a href="<%= windows_path %>"><%= t(:windows) %></a></li>
                <li><a href="<%= pops_path %>"><%= t(:pops) %></a></li>
                <li><a href="<%= hints_path %>"><%= t(:hints) %></a></li>
            </ul>
        </li>
        <li class="">
            <a class="dropdown-toggle" href="#"><span class="icn-target icon"></span><%= t(:controls) %></a>
            <ul class="d-menu" data-role="dropdown" style="display: none;">
                <li><a href="<%= accordion_path %>"><%= t(:accordion) %></a></li>
                <li><a href="<%= tabs_path %>"><%= t(:tabs) %></a></li>
                <li><a href="<%= treeview_path %>"><%= t(:treeview) %></a></li>
                <li><a href="<%= listview_path %>"><%= t(:listview) %></a></li>
                <li><a href="<%= slider_path %>"><%= t(:slider) %></a></li>
                <li><a href="<%= wizards_path %>"><%= t(:wizards) %></a></li>
            </ul>
        </li>
        <li class="">
            <a class="dropdown-toggle" href="#"><span class="icn-calendar icon"></span><%= t(:datetime) %></a>
            <ul class="d-menu" data-role="dropdown" style="display: none;">
                <li><a href="<%= calendar_path %>"><%= t(:calendar) %></a></li>
                <li><a href="<%= datepicker_path %>"><%= t(:datepicker) %></a></li>
                <li><a href="<%= countdown_path %>"><%= t(:countdown) %></a></li>
            </ul>
        </li>
        <li class="">
            <a class="dropdown-toggle" href="#"><span class="icn-file-play icon"></span><%= t(:media) %></a>
            <ul class="d-menu" data-role="dropdown" style="display: none;">
                <li><a href="<%= audio_player_path %>"><%= t(:audio_player) %></a></li>
                <li><a href="<%= video_player_path %>"><%= t(:video_player) %></a></li>
            </ul>
        </li>
        <li class="">
            <a class="dropdown-toggle" href="#"><span class="icn-plus icon"></span><%= t(:thirdparty) %></a>
            <ul class="d-menu" data-role="dropdown" style="display: none;">
                <li><a href="<%= select2_path %>"><%= t(:select2) %></a></li>
                <li><a href="<%= data_tables_path %>"><%= t(:data_tables) %></a></li>
                <li><a href="<%= animate_path %>"><%= t(:animate) %></a></li>
            </ul>
        </li>
        <li class="">
            <a class="dropdown-toggle" href="#"><span class="icn-cog icon"></span><%= t(:utils) %></a>
            <ul class="d-menu" data-role="dropdown" style="display: none;">
                <li><a href="<%= dark_mode_path %>"><%= t(:dark_mode) %></a></li>
                <li><a href="<%= easing_path %>"><%= t(:easing) %></a></li>
                <li><a href="<%= reqjs_path %>"><%= t(:reqjs) %></a></li>
            </ul>
        </li>
        <li class="">
            <a class="dropdown-toggle" href="#"><span class="icn-users icon"></span><%= t(:community) %></a>
            <ul class="d-menu" data-role="dropdown" style="display: none;">
                <li><a href="https://www.facebook.com/ajspektor/">Facebook</a></li>
                    <li><a href="https://github.com/sutherland007/Alacran-CSS">Github</a></li>
                    <li class="divider"></li>
                    <li><a href="license.html">License</a></li>
            </ul>
        </li>
    </ul>
</div>

<!--<div class="build-string">
    <p>Alacrán UI</p>
    <p>Build 9052020</p>
</div>-->
<style type="text/css">
    .sidebar2{
        background: transparent;
        border: none;
    }
    .d-menu{
        background: transparent;
    }
    .sidebar2 li.active a{
        background-color: #3c3c3c;
    }
    .sidebar2 li:hover a{
        background-color: #808080;
    }
    .sidebar2 li a{
        background: transparent;
        color: #ffffff;
    }
    .sidebar2 li li:not(:hover) a{
        background: transparent;
    }
    .sidebar2 li:hover{
        background: transparent;
    }
</style>

app/views/home/about.html.erb
<%= render 'bar' %>
<h1>about me</h1>

app/views/home/index.html.erb
<%= render 'bar' %>
<%= title t(:frame_index) %>
<div id="sec1" style="text-align: center;">
            <div id="Sec1Content" class="fg-white">
                <h1 style="font-size: 3.5rem; line-height: 1" class="text-shadow alacran-title text-light"><%= t(:frame_index) %></h1>
                <div class="padding30 sub-leader text-light">
                    <%= t(:frame_desc) %>
                </div>
                <div style="text-align: center;">
                	<a href="https://github.com/sutherland007/Alacran-UI/releases/download/build-9052020/Alacran.UI.Build.9052020.rar" class="button large-button primary" style="padding-top: 0;"><%= t(:download) %></a>
                	<a href="https://github.com/sutherland007/Alacran-CSS" class="button large-button success" style="padding-top: 0;"><%= t(:github) %></a>
                </div>
            </div>
</div>

<div style="text-align: center;">
            <h1 style="text-align: center;"><%= t(:browsers) %></h1>
            <div class="grid">
                <div class="row cells4">
                    <div class="cell">
                        <p><span class="icn-firefox icn-4x"></span> FireFox</p>
                    </div>

                    <div class="cell">
                        <p><span class="icn-edge icn-4x"></span> Microsoft Edge</p>
                    </div>

                    <div class="cell">
                        <p><span class="icn-opera icn-4x"></span> Opera</p>
                    </div>

                    <div class="cell">
                        <p><span class="icn-chrome icn-4x"></span> Google Chrome</p>
                    </div>
                </div>
            </div>
</div>

<div style="background-color: #674AD4; color: #FFF;">
	<h2 style="text-align: center; padding-top: 20px;"><%= t(:about_sec_title) %></h2>
	<div class="flex-grid">
		<div class="row cell-auto-size flex-just-center">
			<div class="cell colspan2"><%= image_tag("changes.png", size: "256x256") %></div>

			<div class="cell colspan5">
				<h4><%= t(:para_home_1) %></h4>
			</div>
		</div>
	</div>

	<div class="flex-grid">
		<div class="row cell-auto-size flex-just-center">
			<div class="cell colspan5">
				<h4><%= t(:para_home_2) %></h4>
			</div>

			<div class="cell colspan2">
				<%= image_tag("alr-ui-logo.png", size: "200x200") %>
			</div>
		</div>
	</div>

	<div style="text-align: center; padding-bottom: 20px;">
		<a href="/about" class="button large-button success" style="padding-top: 0;"><%= t(:cta_about) %></a>			
	</div>
	
</div>

<div>
	<h2 style="text-align: center"><%= t(:get_st_title) %></h2>
		<div class="step-circle">
			<a class="step-number">1</a>
		</div>


		<li>
			<h4><%= t(:step_1) %></h4>
		</li>
		<li>
			<h4><%= t(:step_2) %></h4>
		</li>
		<li>
			<h4><%= t(:step_3) %></h4>
		</li>
		<li>
			<h4><%= t(:step_q) %> <a onclick="toggleMetroCharm('#docs-charm')" style="cursor: pointer;"><%= t(:step_q_2) %></a></h4>
		</li>
		<li>
			<h4><%= t(:step_warn) %></h4>

</div>

app/views/layouts/_flash.html.erb
<script>
<% flash.each do |type, message| %>
	var altype = '<%= alerter(type) %>'
	var altitle = "notify"
	var aicon = "<span class='icn-bubble'></span>"
	var notype = "notify"

	if (altype === 'success' || altype === 'notice'){
		altitle = "<%= t(:sucss) %>"
		aicon = "<span class='icn-checkmark'></span>"
		notype = 'success'
	}
	else if (altype === 'alert'){
		altitle = "<%= t(:alertr) %>"
		aicon = "<span class='icn-warning'></span>"
		notype = 'alert'
	}
	else if (altype === 'warning'){
		altitle = "<%= t(:warnr) %>"
		aicon = "<span class='icn-warning'></span>"
		notype = 'warning'
	}
	else if (altype === 'info'){
		altitle = "<%= t(:infor) %>"
		aicon = "<span class='icn-bubble'></span>"
		notype = 'info'
	}

  $.Notify({
    		caption: altitle,
    		content: '<%= message %>',
    		keepOpen: true,
    		icon: aicon,
    		type: notype
		});
<% end %>

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title><%= yield(:title) %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  	<%= render 'layouts/flash', flash: flash %>
    <%= yield %>
  </body>
</html>